/**
 * Canonical copy-paste prompts vendored from img2threejs `main` at d6815db.
 * Source: https://github.com/img2threejs/img2threejs/tree/main/docs/standard-prompts
 * Keep wording exact; only labels and source metadata belong to the showcase.
 */
export interface StandardPrompt {
  id: string;
  label: string;
  sourceUrl: string;
  prompt: string;
}

const SOURCE_ROOT = 'https://github.com/img2threejs/img2threejs/blob/main/docs/standard-prompts';

export const STANDARD_PROMPTS: readonly StandardPrompt[] = [
  {
    id: "build",
    label: "Build",
    sourceUrl: `${SOURCE_ROOT}/build.md`,
    prompt: [
      "Rebuild the subject in this reference as a procedural Three.js model, using img2threejs.",
      "",
      "## Inputs",
      "- Reference:      <ABSOLUTE_PATH_TO_IMAGE>",
      "- Subject name:   <SubjectName>",
      "- Demo id:        <subject-id>",
      "- Profile:        <character | animated-character | object>",
      "- Real longest dimension: <e.g. 1.70 m>   # sanity-checks scale; never used to scale",
      "",
      "## Step 0 — Can this subject be built at all?",
      "",
      "Segment the figure from the background and report as numbers:",
      "  · width/height at the hip band (48-54% of figure height), knee (68-74%), ankle (92-99%)",
      "  · silhouette area / height²",
      "  · whether the silhouette WIDENS below the hip, and by how much",
      "",
      "The character template is 61 anatomy components and ZERO garments — clothing is not shipped in",
      "v1.5. If a meaningful share of the silhouette is cloth standing away from the body (flared skirt,",
      "hanging sleeve, cape, trailing panel), STOP HERE and tell me: what fraction, and what will be lost.",
      "A body-shaped figure delivered under the subject's name is the failure this step exists to prevent.",
      "For a subject like that the GLB route is the honest one — say so and stop.",
      "",
      "## Step 1 — Intake",
      "",
      "    python3 forge/state.py init --state .img2threejs/state.json \\",
      "      --reference <image> --profile <profile> --spec object-sculpt-spec.json",
      "    python3 forge/stage1_intake/probe_image.py <image>",
      "    python3 forge/stage1_intake/extract_landmarks.py <image> \\",
      "      --out anatomy.json --overlay overlay.png",
      "    python3 forge/stage1_intake/build_detail_inventory.py <image> \\",
      "      --mode component-zones --out detail-inventory.json",
      "",
      "Two things about the overlay, both measured, both worth knowing before you trust it:",
      "  · it divides the IMAGE height, not the figure's bounding box, so every guide is offset by",
      "    whatever margin sits above the head. Re-read the guides against the figure top.",
      "  · `styleHeads` defaults to 6.0. Measure the head against the figure and set the real value;",
      "    on a stylized 8-head figure the default puts the \"nose base\" guide on the eyes.",
      "",
      "## Step 2 — Assess. This is YOUR work, not the script's.",
      "",
      "Open the assessment and fill it from looking at the reference. Nothing downstream can succeed",
      "until these hold real values:",
      "",
      "    preSpecAssessment.objectClass.primaryType      not \"unassessed\"",
      "    preSpecAssessment.objectClass.primaryDomain    object | character | hybrid",
      "    objectClass.formLanguage / structureKind / motionPotential / materialFamilies   non-empty",
      "    complexity.scores       all eight, from what you see, not defaults",
      "    complexity.estimatedCounts                     real counts",
      "    detailInventory                                >= targetMinDetails entries",
      "    anatomy.applies = true, with styleHeads, proportions, pose, faceLandmarks",
      "",
      "Enumerate the identity-defining details first — bevels and rounding, panel seams, fasteners,",
      "engraved or painted linework, gloss vs matte zones, wear. Drop any detail you cannot place on a",
      "real component rather than faking it.",
      "",
      "## Step 3 — Spec, then gate",
      "",
      "    python3 forge/stage2_spec/new_sculpt_spec.py \"<SubjectName>\" --image <image> \\",
      "      --assessment assessment.json --out object-sculpt-spec.json",
      "    python3 forge/stage2_spec/validate_sculpt_spec.py object-sculpt-spec.json --strict-quality",
      "",
      "Expect failures on the first run. Read each cause and answer it — a missing",
      "`colorMaterialRecipe` means derive that component's colour from the reference pixels, not that the",
      "gate is wrong. Iterate until it exits 0.",
      "",
      "Only then:",
      "",
      "    python3 forge/stage3_build/generate_threejs_factory.py object-sculpt-spec.json \\",
      "      --out src/create<SubjectName>Model.ts",
      "",
      "The generator repeats the gate and is fail-closed: on failure it exits 2 with",
      "`{\"status\":\"BLOCKED\", ...}` and writes NO file. If you see that, the spec is not ready — go back to",
      "Step 2. Never pass `--allow-nonstrict`.",
      "",
      "## Step 4 — Render and review, one pass at a time",
      "",
      "Render, package one reference-vs-render sheet, and judge it. Do not advance a pass until its",
      "review passes. Record per-region confidence for anything the single view cannot show.",
      "",
      "## When to stop, and when not to",
      "",
      "STOP and ask me:",
      "  · Step 0 says the subject is mostly cloth",
      "  · a gate fails for a reason you cannot resolve from the reference",
      "  · `next.py` exits 3 / `status=stopped`",
      "",
      "DO NOT stop for:",
      "  · a scaffolded field being empty — fill it, that is the job",
      "  · strict-quality failing on the first run — read the causes and answer them",
      "  · a detail you cannot place — drop it, note it, continue",
      "",
      "## Report",
      "",
      "Components · strict-quality exit and cause count · passes cleared · details inventoried vs target ·",
      "per-region confidence · and one line naming what still does not match. Never say \"done\" when it is",
      "\"improved\".",
    ].join('\n'),
  },
  {
    id: "glb-force-measured",
    label: "GLB Force-Measured",
    sourceUrl: `${SOURCE_ROOT}/glb-force-measured.md`,
    prompt: [
      "Build this subject with every parameter the GLB measures FORCED to its measured value.",
      "",
      "## Inputs",
      "- GLB (measurement instrument): <ABSOLUTE_PATH_TO_GLB>",
      "- Reference image (optional):   <PATH_OR_NONE>",
      "- Subject name:  <SubjectName>",
      "- Demo id:       <subject-id>",
      "- Overwrite:     <yes | no>     # yes = replace an existing demo of this id in place",
      "",
      "## Contract",
      "",
      "The GLB is measured, never shipped. Symlink it somewhere gitignored; the running demo must fetch no",
      "`.glb` and no `.bin`. Texture images are not copied — appearance is carried as per-vertex colour.",
      "The deliverable is TypeScript.",
      "",
      "Part names are HYPOTHESES from measured bounds and must say so. On a rigged mesh the BONE names are",
      "the rig's own and must NOT carry that caveat.",
      "",
      "## Step 1 — Ask the bytes what the file is, before decoding it",
      "",
      "    python3 forge/stage1_intake/probe_glb.py <glb> --out glb-probe.json",
      "",
      "`skinCount` and `animationCount` decide the route:",
      "  · skinCount == 0        static: parts stay separate, an LOD ladder is allowed",
      "  · skinCount >= 1        rigged: read the skin, never author one beside it. See Step 3.",
      "  · skinCount > 1         choose one explicitly and say why",
      "  · animationCount > 0    clips are measured too, keyed to BONE INDEX, never to bone name",
      "",
      "## Step 2 — Measure, then force",
      "",
      "Take every parameter in the table above from the GLB and write the measured value into the spec.",
      "Where the pipeline would normally infer, it must not: name each forced field and the number it took.",
      "",
      "Keep vertices in the space the file put them in. For a rigged mesh that is BIND space — the space",
      "the inverse bind matrices are expressed in. Normalisation is a TRANSFORM, never an edit to the",
      "buffer: scale on the mesh so bones parented to it scale with the skin, offset on the group. Editing",
      "vertices to normalise moves the mesh out from under its own skeleton.",
      "",
      "Per-vertex colour is sampled from the base-colour TEXTURE at each vertex UV, not from a `color`",
      "attribute. A rigged GLB typically ships UVs and a texture and no vertex colours at all; reading only",
      "the attribute makes every vertex fall back to the flat base colour and the figure comes out white.",
      "The texture is sRGB bytes and the material factor is linear: apply the factor in linear space, then",
      "convert back.",
      "",
      "## Step 3 — If it is rigged, four rules, none negotiable",
      "",
      "1. ONE detail level. Do not decimate. Decimation rewrites the vertex list while `skinIndex` /",
      "   `skinWeight` are per-vertex — every weight would address a vertex that no longer exists and the",
      "   figure tears apart the moment a clip plays. It looks perfect until then.",
      "2. ONE skinned shell, not named parts. Rigging merges the mesh; advertising per-part pivots would be",
      "   a contract the geometry cannot honour. Expose the skeleton instead.",
      "3. Bones parents-first, `parent` as an INDEX with `-1` for a root, clip tracks keyed to bone index.",
      "   A clip naming a bone the skeleton does not have is DROPPED and named in the report — never bound",
      "   to whatever happens to sit at that index.",
      "4. `updateMatrixWorld(true)` BEFORE constructing the Skeleton. `calculateInverses()` reads each",
      "   bone's current world matrix; built in the wrong order it captures identity, the rest pose never",
      "   cancels, and the model renders a corpse while reporting `bound: true`.",
      "",
      "## Step 4 — Parity gates. These REPLACE the fidelity gates and are stricter, not looser.",
      "",
      "Report each as a number, not a verdict:",
      "",
      "    vertex count        emitted vs measured     EQUAL",
      "    triangle count      emitted vs measured     EQUAL",
      "    bounding box        emitted vs measured     within the quantisation step",
      "    base colour         per part                within the stated tolerance",
      "    roughness/metalness per part                EQUAL to the measured value or median",
      "    Σ skin weights      per vertex              |Σw - 1| < 1e-5",
      "    skinIndex range     every index             < bone count",
      "    bone count          emitted vs measured     EQUAL",
      "    clip count          emitted vs measured     EQUAL, or the difference named clip by clip",
      "    clip duration       per clip                EQUAL",
      "    binding delta       seek each clip to >= 5 times    <= 2^-23",
      "",
      "The last one is the only check that separates a clip that PLAYS from one that merely exists, loads,",
      "holds an action and reports a duration while driving nothing.",
      "",
      "A parity gate that cannot be evaluated reports `unevaluated` with the missing input named. Never a",
      "pass.",
      "",
      "## Step 5 — Emit",
      "",
      "Factory, embedded surface data, codec and spec — all TypeScript, nothing fetched at runtime. With",
      "`Overwrite: yes`, replace the files for this demo id and KEEP its id, camera and registry entry;",
      "do not re-litigate settled decisions.",
      "",
      "## What NOT to do on this route",
      "",
      "  · do not run `--strict-quality`; it asks about inference and there is none here. Parity is the gate.",
      "  · do not enumerate a `detailInventory` for geometry the GLB already measured.",
      "  · do not smooth, re-topologise, weld or decimate. Those change the thing you are measuring.",
      "  · do not rename what the file already named.",
      "  · do not stop because a fidelity gate is unhappy. Stop when a PARITY gate fails.",
      "",
      "## Report",
      "",
      "Forced parameters and the value each took · vertex/triangle counts emitted vs measured · bounds",
      "delta · bone count · clips with durations · maxSampledBindingDelta per clip · LOD count · and one",
      "line naming what the GLB could not hand over, from the list above.",
    ].join('\n'),
  },
  {
    id: "polish",
    label: "Polish",
    sourceUrl: `${SOURCE_ROOT}/polish.md`,
    prompt: [
      "Polish this img2threejs build against its reference. One defect per cycle.",
      "",
      "## Inputs",
      "- Factory:    <PATH_TO_create<Name>Model.ts>",
      "- Spec:       <PATH_TO_object-sculpt-spec.json>",
      "- Reference:  <PATH_TO_REFERENCE>",
      "- Budget:     <N> cycles          # stop when spent, and report what is left",
      "",
      "## Cycle",
      "",
      "1. RENDER and package one reference-vs-render sheet. One sheet, not a scattering of screenshots.",
      "",
      "2. NAME the single worst defect in one sentence — what is wrong, where, and how you can tell.",
      "   Rank by identity impact, not by how easy it is to fix. A wrong silhouette outranks a wrong",
      "   gloss, always.",
      "",
      "3. MEASURE it before touching anything. Interior difference banded by height, ΔE00 for a colour,",
      "   silhouette IoU for a shape, per-region confidence for anything the view cannot show. Write the",
      "   number down. \"It looks off\" is not a measurement and cannot be checked afterwards.",
      "",
      "4. ATTRIBUTE it to a component id and a spec field. If you cannot name the field, you are guessing",
      "   — say so and pick the next defect instead of editing blind.",
      "",
      "5. FIX exactly that field. Do not touch a second component in the same cycle, however tempting.",
      "",
      "6. RE-MEASURE the same number. Three outcomes and all three are results:",
      "     improved   -> keep it, record both numbers",
      "     unchanged  -> revert it. The hypothesis was wrong; say what it was.",
      "     worse      -> revert it, and say what that rules out.",
      "",
      "7. Re-run the gates that cover what you touched. Never lower a threshold to pass one.",
      "",
      "## Rules",
      "",
      "  · A cycle that reverts is a successful cycle. It bought information.",
      "  · Never fix two defects at once. Attribution is the whole value here.",
      "  · Never edit the generated factory by hand — edit the spec and regenerate, or the next",
      "    regeneration silently discards your work.",
      "  · If a defect traces to something the reference cannot show, stop and say so: no number of cycles",
      "    will resolve what the image does not contain.",
      "  · If the same defect survives two cycles, stop and report it. A third attempt is guessing.",
      "",
      "## Report",
      "",
      "Per cycle: defect · measured before · field changed · measured after · kept or reverted.",
      "Then: which defects remain, ranked, and which of them the reference cannot resolve.",
      "Say \"improved\", never \"done\", unless every ranked defect is closed.",
    ].join('\n'),
  },
  {
    id: "vfx",
    label: "VFX",
    sourceUrl: `${SOURCE_ROOT}/vfx.md`,
    prompt: [
      "Build the effects layer for the character already in this showcase — the rig and its clips exist,",
      "only the VFX is missing.",
      "",
      "Start from the subject. Study what this character is and how its actions read in the world it",
      "comes from; the effects should belong to it, not to a generic effect kit. Then find the events —",
      "don't eyeball timings off a scrub bar. Sweep every embedded clip through a real AnimationMixer and",
      "measure where a strike actually stops at extension, where weight actually meets the ground, and",
      "where the body is driven by a force arriving from outside the clip. Normalise to figure heights so",
      "the table survives a change of scale.",
      "",
      "Build around the stop, not the travel — the interesting part of any impact is the instant it",
      "arrests. Schedule the effects against that measured table rather than a live \"it just decelerated\"",
      "test: scheduling fires on the exact frame, and it's the only way a windup can exist at all,",
      "because nothing else knows a strike is coming. Add hitstop; the clip itself slowing for a few tens",
      "of milliseconds is most of the felt impact.",
      "",
      "Give the character a small vocabulary of impact kinds and make them differ in motion first, colour",
      "second — a light hit that is only a paler heavy hit is still a heavy hit. Take the palette from",
      "the world the character lives in, not from an element wheel, and keep one contrasting accent so",
      "something in frame reads against the rest. A blow the character takes is not a strike played",
      "backwards: rings turn inward, debris comes off the body, no flash at the hand.",
      "",
      "Calibrate continuous layers — motion trails, breath, ambient drift — per clip against that clip's",
      "own measured speed; one global threshold smears the fast clips and leaves the slow ones bare. Pool",
      "everything, allocate nothing after construction, and start every object invisible so the viewer's",
      "framing pass never measures an effect. Then show me the loudest action, the quietest one, and a",
      "ground contact.",
    ].join('\n'),
  },
];
