/**
 * GENERATED by `node scripts/measure-monster-tree-events.mjs --emit` — do not hand-edit.
 *
 * Where things actually HAPPEN in each embedded clip, found by sweeping it through a real
 * AnimationMixer at 240 Hz and reading the dynamics, not by scrubbing a timeline.
 *
 *   arrest   a limb travelling faster than 1.1 H/s that stops. Recorded at the frame of
 *            greatest DECELERATION, which is the frame the impact happens on — not the frame the
 *            limb was fastest, which is earlier, and not the frame it finally rests, which is later.
 *   plant    weight arriving: a foot below 0.14 H with its vertical velocity crossing from
 *            falling to still.
 *   driven   the body accelerated by something that is not its own limbs — a hip spike above
 *            9 H/s² with no limb arrest within 120 ms. This is what a blow TAKEN looks
 *            like from inside a clip.
 *
 * Everything is normalised to FIGURE HEIGHTS (H = 1.9 model units) and heights are
 * fractions of it, so the table survives a change of scale.
 *
 * `handPeak` and `bodyMean` are each clip's own motion budget. Continuous layers — trails, embers,
 * breath — are calibrated against them per clip: one global threshold smears the fast clips and
 * leaves the slow ones bare. The set spans handPeak 0.134 (fire) to 5.231 (box_02), a factor of 39.
 */

export interface ClipEvent {
  kind: 'arrest' | 'plant' | 'driven';
  bone: string;
  /** Seconds into the clip. */
  at: number;
  /** Deceleration in H/s² for an arrest or a driven spike. */
  decel?: number;
  /** Speed in H/s at the event. */
  speed?: number;
  /** Height above the ground as a fraction of figure height. */
  height?: number;
}

export interface ClipEvents {
  clip: string;
  duration: number;
  /** Fastest hand speed anywhere in the clip, H/s. */
  handPeak: number;
  /** Mean torso speed over the clip, H/s. */
  bodyMean: number;
  events: ClipEvent[];
}

export const FIGURE_HEIGHT = 1.9;

export const CLIP_EVENTS: Record<string, ClipEvents> = {
  'preset:biped:run_upstairs': {
    clip: 'preset:biped:run_upstairs', duration: 0.667, handPeak: 1.183, bodyMean: 0.385,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.066, decel: 72.6 },
      { kind: 'driven', bone: 'Hip', at: 0.335, decel: 26.3 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.501, decel: 102.7, speed: 0.452, height: 0.289 },
      { kind: 'driven', bone: 'Hip', at: 0.634, decel: 9.4 },
    ],
  },
  'preset:biped:standing_relax': {
    clip: 'preset:biped:standing_relax', duration: 14.1, handPeak: 0.103, bodyMean: 0.006,
    events: [],
  },
  'preset:biped:box_01': {
    clip: 'preset:biped:box_01', duration: 1.8, handPeak: 2.201, bodyMean: 0.126,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.067, decel: 9.9 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.375, speed: 0.579, height: 0.13 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.433, decel: 87.2, speed: 0.442, height: 0.104 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.467, decel: 67.4, speed: 0.735, height: 0.609 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.1, decel: 60.7, speed: 0.485, height: 0.102 },
    ],
  },
  'preset:biped:box_02': {
    clip: 'preset:biped:box_02', duration: 2.267, handPeak: 5.231, bodyMean: 0.168,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.433, decel: 13.2 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.508, speed: 0.553, height: 0.081 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.667, decel: 219.1, speed: 0.767, height: 0.032 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.833, decel: 201.8, speed: 0.908, height: 0.581 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1, decel: 203.5, speed: 0.996, height: 0.06 },
      { kind: 'driven', bone: 'Hip', at: 1.133, decel: 14.6 },
      { kind: 'driven', bone: 'Hip', at: 1.333, decel: 24.3 },
      { kind: 'driven', bone: 'Hip', at: 1.633, decel: 44 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.8, decel: 70.7, speed: 0.472, height: 0.606 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.8, decel: 366.5, speed: 2.03, height: 0.687 },
    ],
  },
  'preset:biped:box_03': {
    clip: 'preset:biped:box_03', duration: 2.067, handPeak: 2.349, bodyMean: 0.129,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.3, decel: 9.3 },
      { kind: 'driven', bone: 'Hip', at: 0.533, decel: 24 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.55, speed: 0.712, height: 0.138 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.667, decel: 69, speed: 0.899, height: 0.628 },
      { kind: 'driven', bone: 'Hip', at: 0.867, decel: 9.1 },
    ],
  },
  'preset:biped:defeat_03': {
    clip: 'preset:biped:defeat_03', duration: 4.467, handPeak: 2.156, bodyMean: 0.177,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.4, decel: 9.2 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.533, decel: 42.9, speed: 0.837, height: 0.571 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.733, decel: 54.6, speed: 0.465, height: 0.108 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.812, speed: 0.621, height: 0.083 },
      { kind: 'driven', bone: 'Hip', at: 0.966, decel: 14.6 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.265, decel: 49.6, speed: 0.902, height: 0.133 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.345, speed: 0.643, height: 0.108 },
      { kind: 'driven', bone: 'Hip', at: 1.632, decel: 10 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.998, decel: 52, speed: 0.616, height: 0.217 },
      { kind: 'driven', bone: 'Hip', at: 2.131, decel: 9.4 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.602, decel: 103, speed: 0.906, height: 0.04 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.635, decel: 67.3, speed: 0.934, height: 0.022 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.926, speed: 0.68, height: 0.07 },
    ],
  },
  'preset:biped:fire': {
    clip: 'preset:biped:fire', duration: 1.233, handPeak: 0.134, bodyMean: 0.008,
    events: [],
  },
  'preset:biped:front_kick_01': {
    clip: 'preset:biped:front_kick_01', duration: 2.033, handPeak: 2.351, bodyMean: 0.303,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 14 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.267, decel: 142.4, speed: 0.167, height: 0.038 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.433, decel: 188.8, speed: 0.276, height: 0.407 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.6, decel: 168.4, speed: 0.992, height: 0.504 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.6, decel: 97.7, speed: 0.912, height: 0.576 },
      { kind: 'driven', bone: 'Hip', at: 0.767, decel: 9.6 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.9, decel: 142.1, speed: 0.983, height: 0.839 },
      { kind: 'driven', bone: 'Hip', at: 1.3, decel: 10.1 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.387, speed: 0.83, height: 0.139 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.467, decel: 126.5, speed: 1.392, height: 0.104 },
      { kind: 'driven', bone: 'Hip', at: 1.633, decel: 18.7 },
      { kind: 'driven', bone: 'Hip', at: 1.867, decel: 54.7 },
    ],
  },
  'preset:biped:front_kick_02': {
    clip: 'preset:biped:front_kick_02', duration: 1.133, handPeak: 4.961, bodyMean: 0.542,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 46.9 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.267, decel: 88.4, speed: 0.372, height: 0.041 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.467, decel: 232, speed: 1.432, height: 0.003 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.833, decel: 122, speed: 2.992, height: 0.337 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.979, speed: 0.837, height: 0.139 },
      { kind: 'driven', bone: 'Hip', at: 1.067, decel: 17.3 },
    ],
  },
  'preset:biped:dance_01': {
    clip: 'preset:biped:dance_01', duration: 18.567, handPeak: 3.751, bodyMean: 0.066,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.9, decel: 9.2 },
      { kind: 'driven', bone: 'Hip', at: 1.466, decel: 9.9 },
      { kind: 'plant', bone: 'L_ToeBase', at: 1.575, speed: 0.894, height: 0.071 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.8, decel: 79.7, speed: 0.587, height: 0.031 },
      { kind: 'driven', bone: 'Hip', at: 2.033, decel: 11.2 },
      { kind: 'arrest', bone: 'L_Hand', at: 3.066, decel: 55.1, speed: 0.443, height: 0.656 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.233, decel: 102.7, speed: 0.397, height: 0.056 },
      { kind: 'arrest', bone: 'L_Hand', at: 4.832, decel: 121.8, speed: 0.809, height: 0.444 },
      { kind: 'arrest', bone: 'R_Hand', at: 4.832, decel: 137.6, speed: 0.93, height: 0.556 },
      { kind: 'plant', bone: 'L_ToeBase', at: 6.111, speed: 0.579, height: 0.063 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 6.265, decel: 87.6, speed: 1.026, height: 0.032 },
      { kind: 'driven', bone: 'Hip', at: 6.432, decel: 17.5 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.669, decel: 25.2, speed: 1.296, height: 0.629 },
      { kind: 'arrest', bone: 'L_Hand', at: 6.832, decel: 31.1, speed: 0.701, height: 0.82 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 7.798, decel: 50, speed: 0.82, height: 0.057 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.998, decel: 26.2, speed: 0.432, height: 0.424 },
      { kind: 'driven', bone: 'Hip', at: 9.569, decel: 12.1 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.702, decel: 36.1, speed: 0.761, height: 0.033 },
      { kind: 'driven', bone: 'Hip', at: 9.869, decel: 10.9 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 10.335, decel: 35.2, speed: 0.994, height: 0.053 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 10.768, decel: 42.1, speed: 0.265, height: 0.038 },
      { kind: 'driven', bone: 'Hip', at: 11.168, decel: 9.3 },
      { kind: 'driven', bone: 'Hip', at: 11.402, decel: 11.2 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 11.806, decel: 51.8, speed: 1.127, height: 0.08 },
      { kind: 'arrest', bone: 'L_Hand', at: 12.835, decel: 55.3, speed: 0.22, height: 0.456 },
      { kind: 'arrest', bone: 'R_Hand', at: 15.001, decel: 48, speed: 0.757, height: 0.509 },
      { kind: 'arrest', bone: 'L_Hand', at: 16.667, decel: 104.8, speed: 0.788, height: 0.494 },
    ],
  },
  'preset:biped:dance_02': {
    clip: 'preset:biped:dance_02', duration: 10.267, handPeak: 3.626, bodyMean: 0.29,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 28.1 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.2, decel: 114.1, speed: 0.506, height: 0.023 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.321, speed: 2.023, height: 0.136 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.367, decel: 71, speed: 0.649, height: 0.718 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.433, decel: 158.1, speed: 0.164, height: 0.508 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.433, decel: 206.7, speed: 0.474, height: 0.028 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.6, decel: 112.8, speed: 0.873, height: 0.038 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.754, speed: 1.244, height: 0.136 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.833, decel: 124.4, speed: 0.385, height: 0.537 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.833, decel: 216.8, speed: 0.527, height: 0.734 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.833, decel: 130, speed: 0.941, height: 0.042 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.833, decel: 163.3, speed: 0.644, height: 0.033 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.067, decel: 102.1, speed: 1.99, height: 0.452 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.067, decel: 110.8, speed: 0.587, height: 0.025 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.179, speed: 2.69, height: 0.135 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.233, decel: 114.4, speed: 0.501, height: 0.735 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.233, decel: 143.8, speed: 1.464, height: 0.052 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.467, decel: 141.8, speed: 0.914, height: 0.026 },
      { kind: 'plant', bone: 'L_ToeBase', at: 1.604, speed: 1.358, height: 0.137 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.633, decel: 153.9, speed: 1.328, height: 0.517 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.7, decel: 121.6, speed: 0.345, height: 0.72 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.7, decel: 103.8, speed: 0.778, height: 0.038 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.867, decel: 105.4, speed: 1.096, height: 0.041 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.033, decel: 95.3, speed: 1.066, height: 0.696 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.033, decel: 149.9, speed: 1.398, height: 0.465 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.042, speed: 2.864, height: 0.137 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.1, decel: 95.5, speed: 0.908, height: 0.029 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.1, decel: 139.1, speed: 1.47, height: 0.037 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.367, decel: 103, speed: 0.302, height: 0.018 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.433, decel: 116, speed: 1.354, height: 0.628 },
      { kind: 'plant', bone: 'L_ToeBase', at: 2.467, speed: 2.032, height: 0.136 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.5, decel: 79.6, speed: 1.196, height: 0.519 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.6, decel: 144.2, speed: 0.066, height: 0.033 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.767, decel: 100.7, speed: 0.638, height: 0.039 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.833, decel: 82.2, speed: 1.332, height: 0.642 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.879, speed: 1.858, height: 0.138 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.9, decel: 86.9, speed: 1.132, height: 0.479 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 3, decel: 132.6, speed: 0.297, height: 0.025 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3, decel: 100.6, speed: 0.365, height: 0.029 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.233, decel: 136.1, speed: 0.501, height: 0.018 },
      { kind: 'arrest', bone: 'L_Hand', at: 3.3, decel: 67.1, speed: 1.194, height: 0.491 },
      { kind: 'plant', bone: 'L_ToeBase', at: 3.308, speed: 1.601, height: 0.126 },
      { kind: 'arrest', bone: 'R_Hand', at: 3.4, decel: 130.9, speed: 0.511, height: 0.718 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 3.4, decel: 102.8, speed: 0.674, height: 0.036 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.4, decel: 111.7, speed: 0.552, height: 0.039 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 3.633, decel: 80, speed: 0.612, height: 0.022 },
      { kind: 'plant', bone: 'R_ToeBase', at: 3.767, speed: 2.215, height: 0.137 },
      { kind: 'arrest', bone: 'L_Hand', at: 3.8, decel: 86.7, speed: 0.86, height: 0.779 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.867, decel: 188.7, speed: 0.673, height: 0.026 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.033, decel: 159.4, speed: 0.837, height: 0.031 },
      { kind: 'plant', bone: 'L_ToeBase', at: 4.162, speed: 1.646, height: 0.137 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.267, decel: 258.3, speed: 1.432, height: 0.033 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.267, decel: 171.8, speed: 0.737, height: 0.025 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.433, decel: 89.7, speed: 0.969, height: 0.035 },
      { kind: 'plant', bone: 'L_ToeBase', at: 4.625, speed: 1.551, height: 0.139 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.667, decel: 131, speed: 2.02, height: 0.089 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.667, decel: 154.6, speed: 1.099, height: 0.031 },
      { kind: 'driven', bone: 'Hip', at: 4.833, decel: 77.3 },
      { kind: 'plant', bone: 'R_ToeBase', at: 5.054, speed: 1.293, height: 0.14 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 5.167, decel: 81.7, speed: 0.397, height: 0.025 },
      { kind: 'arrest', bone: 'L_Hand', at: 5.233, decel: 264.8, speed: 2.267, height: 0.532 },
      { kind: 'arrest', bone: 'R_Hand', at: 5.233, decel: 319.1, speed: 1.108, height: 0.63 },
      { kind: 'arrest', bone: 'R_Hand', at: 5.4, decel: 167.7, speed: 2.628, height: 0.56 },
      { kind: 'plant', bone: 'R_ToeBase', at: 5.45, speed: 1.537, height: 0.137 },
      { kind: 'arrest', bone: 'L_Hand', at: 5.567, decel: 125.9, speed: 0.31, height: 0.709 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 5.567, decel: 165.1, speed: 0.278, height: 0.027 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 5.633, decel: 123.5, speed: 0.265, height: 0.035 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 5.867, decel: 127, speed: 1.242, height: 0.226 },
      { kind: 'arrest', bone: 'L_Hand', at: 5.967, decel: 132.9, speed: 0.423, height: 0.691 },
      { kind: 'arrest', bone: 'R_Hand', at: 5.967, decel: 178.1, speed: 0.428, height: 0.712 },
      { kind: 'plant', bone: 'L_ToeBase', at: 6.083, speed: 1.292, height: 0.136 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.1, decel: 133.8, speed: 2.414, height: 0.532 },
      { kind: 'arrest', bone: 'L_Hand', at: 6.2, decel: 64.3, speed: 1.731, height: 0.565 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 6.267, decel: 108.3, speed: 0.501, height: 0.028 },
      { kind: 'driven', bone: 'Hip', at: 6.433, decel: 76.3 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.667, decel: 177.3, speed: 1.509, height: 0.633 },
      { kind: 'driven', bone: 'Hip', at: 6.833, decel: 78.7 },
      { kind: 'arrest', bone: 'R_Hand', at: 7, decel: 127.3, speed: 1.573, height: 0.543 },
      { kind: 'arrest', bone: 'L_Hand', at: 7.067, decel: 130.3, speed: 0.538, height: 0.714 },
      { kind: 'driven', bone: 'Hip', at: 7.233, decel: 68.6 },
      { kind: 'plant', bone: 'R_ToeBase', at: 7.242, speed: 0.744, height: 0.125 },
      { kind: 'driven', bone: 'Hip', at: 7.467, decel: 45 },
      { kind: 'driven', bone: 'Hip', at: 7.7, decel: 36.4 },
      { kind: 'plant', bone: 'R_ToeBase', at: 8.004, speed: 0.737, height: 0.138 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.033, decel: 192.4, speed: 0.666, height: 0.133 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.267, decel: 224.7, speed: 1.435, height: 0.235 },
      { kind: 'plant', bone: 'R_ToeBase', at: 8.4, speed: 1.212, height: 0.136 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.433, decel: 116.1, speed: 0.37, height: 0.679 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.667, decel: 230.2, speed: 1.212, height: 0.286 },
      { kind: 'arrest', bone: 'L_Hand', at: 8.833, decel: 91.7, speed: 0.913, height: 0.712 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.833, decel: 140.7, speed: 1.067, height: 0.567 },
      { kind: 'plant', bone: 'R_ToeBase', at: 8.842, speed: 2.138, height: 0.115 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 8.9, decel: 112.1, speed: 0.987, height: 0.029 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.9, decel: 80.7, speed: 0.972, height: 0.041 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.167, decel: 93.7, speed: 0.376, height: 0.019 },
      { kind: 'arrest', bone: 'L_Hand', at: 9.233, decel: 77.3, speed: 1.335, height: 0.468 },
      { kind: 'arrest', bone: 'R_Hand', at: 9.233, decel: 141.9, speed: 1.393, height: 0.61 },
      { kind: 'plant', bone: 'L_ToeBase', at: 9.292, speed: 1.54, height: 0.135 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.4, decel: 176.5, speed: 0.277, height: 0.031 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.567, decel: 88.6, speed: 0.632, height: 0.038 },
      { kind: 'arrest', bone: 'L_Hand', at: 9.633, decel: 79.7, speed: 1.367, height: 0.596 },
      { kind: 'arrest', bone: 'R_Hand', at: 9.633, decel: 133.5, speed: 1.793, height: 0.425 },
      { kind: 'plant', bone: 'R_ToeBase', at: 9.725, speed: 2.195, height: 0.135 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.8, decel: 139.3, speed: 0.47, height: 0.027 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.8, decel: 177.7, speed: 0.976, height: 0.031 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 10.033, decel: 138.3, speed: 0.516, height: 0.02 },
      { kind: 'plant', bone: 'L_ToeBase', at: 10.162, speed: 1.822, height: 0.139 },
      { kind: 'arrest', bone: 'R_Hand', at: 10.2, decel: 124.1, speed: 0.87, height: 0.713 },
    ],
  },
  'preset:biped:dance_03': {
    clip: 'preset:biped:dance_03', duration: 10.267, handPeak: 3.964, bodyMean: 0.29,
    events: [
      { kind: 'driven', bone: 'Hip', at: 0.033, decel: 55.5 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.2, decel: 204, speed: 0.769, height: 0.027 },
      { kind: 'plant', bone: 'R_ToeBase', at: 0.308, speed: 2.887, height: 0.122 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.367, decel: 129, speed: 1.451, height: 0.041 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.433, decel: 312.3, speed: 0.135, height: 0.653 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.433, decel: 189.7, speed: 0.563, height: 0.635 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.433, decel: 172.4, speed: 0.488, height: 0.033 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.6, decel: 109.7, speed: 0.813, height: 0.041 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.667, decel: 403.1, speed: 0.539, height: 0.276 },
      { kind: 'plant', bone: 'L_ToeBase', at: 0.737, speed: 1.9, height: 0.14 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.833, decel: 138.8, speed: 0.864, height: 0.582 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.833, decel: 270.6, speed: 1.247, height: 0.66 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 0.833, decel: 219.1, speed: 1.008, height: 0.024 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 0.833, decel: 155.2, speed: 0.714, height: 0.046 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.067, decel: 115.8, speed: 0.63, height: 0.023 },
      { kind: 'plant', bone: 'R_ToeBase', at: 1.175, speed: 2.851, height: 0.116 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.233, decel: 237, speed: 0.93, height: 0.671 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.233, decel: 107.6, speed: 0.979, height: 0.044 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.233, decel: 252.2, speed: 1.214, height: 0.031 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.3, decel: 169.8, speed: 0.384, height: 0.62 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.467, decel: 212.6, speed: 2.026, height: 0.223 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 1.467, decel: 117.3, speed: 0.839, height: 0.031 },
      { kind: 'plant', bone: 'L_ToeBase', at: 1.604, speed: 2.58, height: 0.138 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.633, decel: 157.2, speed: 1.349, height: 0.533 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.633, decel: 171.7, speed: 1.733, height: 0.625 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.7, decel: 104.6, speed: 0.942, height: 0.029 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.867, decel: 245.6, speed: 2.525, height: 0.491 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 1.867, decel: 126.4, speed: 1.247, height: 0.03 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.042, speed: 2.319, height: 0.13 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.1, decel: 103.8, speed: 0.984, height: 0.07 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.1, decel: 184.9, speed: 1.53, height: 0.043 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.367, decel: 93.3, speed: 0.306, height: 0.028 },
      { kind: 'plant', bone: 'L_ToeBase', at: 2.471, speed: 3.102, height: 0.134 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.5, decel: 112.7, speed: 1.808, height: 0.578 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.5, decel: 195.4, speed: 2.617, height: 0.069 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.5, decel: 71.7, speed: 1.081, height: 0.039 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.6, decel: 166.3, speed: 0.312, height: 0.573 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 2.767, decel: 138.3, speed: 0.671, height: 0.034 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.833, decel: 125.4, speed: 1.761, height: 0.418 },
      { kind: 'plant', bone: 'R_ToeBase', at: 2.867, speed: 2.617, height: 0.13 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.9, decel: 81, speed: 1.066, height: 0.594 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.9, decel: 151.5, speed: 1.766, height: 0.067 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 3, decel: 134.2, speed: 0.742, height: 0.113 },
      { kind: 'plant', bone: 'L_ToeBase', at: 3.075, speed: 0.955, height: 0.117 },
      { kind: 'arrest', bone: 'L_Hand', at: 3.167, decel: 109.7, speed: 0.325, height: 0.519 },
      { kind: 'plant', bone: 'R_ToeBase', at: 3.287, speed: 0.805, height: 0.138 },
      { kind: 'arrest', bone: 'R_Hand', at: 3.4, decel: 113.6, speed: 0.497, height: 0.614 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.4, decel: 174.5, speed: 0.558, height: 0.034 },
      { kind: 'driven', bone: 'Hip', at: 3.633, decel: 78.4 },
      { kind: 'plant', bone: 'L_ToeBase', at: 3.717, speed: 2.367, height: 0.139 },
      { kind: 'arrest', bone: 'R_Hand', at: 3.8, decel: 207.3, speed: 1.002, height: 0.685 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 3.8, decel: 204.9, speed: 0.909, height: 0.035 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.8, decel: 120.2, speed: 0.543, height: 0.04 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.033, decel: 133.5, speed: 0.529, height: 0.024 },
      { kind: 'plant', bone: 'R_ToeBase', at: 4.154, speed: 2.934, height: 0.132 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.2, decel: 145.5, speed: 1.592, height: 0.06 },
      { kind: 'arrest', bone: 'L_Hand', at: 4.267, decel: 241.6, speed: 0.393, height: 0.727 },
      { kind: 'arrest', bone: 'R_Hand', at: 4.267, decel: 192.4, speed: 0.807, height: 0.644 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.267, decel: 130.6, speed: 0.585, height: 0.042 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.433, decel: 181.4, speed: 0.902, height: 0.036 },
      { kind: 'plant', bone: 'L_ToeBase', at: 4.587, speed: 1.885, height: 0.136 },
      { kind: 'arrest', bone: 'L_Hand', at: 4.6, decel: 154, speed: 1.126, height: 0.502 },
      { kind: 'arrest', bone: 'R_Hand', at: 4.667, decel: 220.7, speed: 0.942, height: 0.621 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.667, decel: 188.9, speed: 1.121, height: 0.035 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.667, decel: 117.9, speed: 0.711, height: 0.035 },
      { kind: 'arrest', bone: 'R_Hand', at: 4.833, decel: 235.4, speed: 1.769, height: 0.462 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 4.833, decel: 185.4, speed: 0.756, height: 0.027 },
      { kind: 'plant', bone: 'R_ToeBase', at: 5.008, speed: 0.567, height: 0.074 },
      { kind: 'arrest', bone: 'R_Hand', at: 5.067, decel: 118.3, speed: 1.3, height: 0.582 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 5.067, decel: 128.1, speed: 0.717, height: 0.038 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 5.233, decel: 91.6, speed: 1.331, height: 0.034 },
      { kind: 'driven', bone: 'Hip', at: 5.367, decel: 9.7 },
      { kind: 'plant', bone: 'R_ToeBase', at: 5.408, speed: 2.549, height: 0.127 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 5.567, decel: 129.7, speed: 0.118, height: 0.033 },
      { kind: 'driven', bone: 'Hip', at: 5.767, decel: 13.9 },
      { kind: 'arrest', bone: 'L_Hand', at: 5.967, decel: 112.9, speed: 0.601, height: 0.596 },
      { kind: 'arrest', bone: 'R_Hand', at: 5.967, decel: 131.1, speed: 0.784, height: 0.655 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 5.967, decel: 84.4, speed: 0.191, height: 0.046 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.2, decel: 252.1, speed: 2.105, height: 0.426 },
      { kind: 'plant', bone: 'L_ToeBase', at: 6.208, speed: 0.716, height: 0.077 },
      { kind: 'arrest', bone: 'L_Hand', at: 6.367, decel: 183.9, speed: 0.687, height: 0.68 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 6.367, decel: 123.1, speed: 0.39, height: 0.042 },
      { kind: 'driven', bone: 'Hip', at: 6.5, decel: 16.4 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 6.667, decel: 97.8, speed: 1.445, height: 0.048 },
      { kind: 'arrest', bone: 'L_Hand', at: 6.833, decel: 346, speed: 0.525, height: 0.694 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.833, decel: 335.6, speed: 0.547, height: 0.616 },
      { kind: 'arrest', bone: 'L_Hand', at: 7, decel: 251.8, speed: 0.561, height: 0.416 },
      { kind: 'plant', bone: 'R_ToeBase', at: 7.117, speed: 1.172, height: 0.139 },
      { kind: 'arrest', bone: 'R_Hand', at: 7.233, decel: 376.1, speed: 0.863, height: 0.818 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 7.233, decel: 76.7, speed: 0.355, height: 0.043 },
      { kind: 'arrest', bone: 'R_Hand', at: 7.467, decel: 226.7, speed: 0.754, height: 0.455 },
      { kind: 'plant', bone: 'R_ToeBase', at: 7.583, speed: 1.055, height: 0.14 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 7.7, decel: 106.1, speed: 0.464, height: 0.043 },
      { kind: 'plant', bone: 'R_ToeBase', at: 7.992, speed: 1.122, height: 0.136 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.033, decel: 96.8, speed: 1.004, height: 0.103 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.1, decel: 178, speed: 0.055, height: 0.721 },
      { kind: 'driven', bone: 'Hip', at: 8.267, decel: 54.3 },
      { kind: 'arrest', bone: 'L_Hand', at: 8.433, decel: 135.4, speed: 1.02, height: 0.698 },
      { kind: 'plant', bone: 'R_ToeBase', at: 8.458, speed: 1.98, height: 0.134 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.5, decel: 150.8, speed: 0.849, height: 0.664 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.6, decel: 94.3, speed: 0.344, height: 0.022 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.733, decel: 135.2, speed: 0.943, height: 0.153 },
      { kind: 'plant', bone: 'R_ToeBase', at: 8.792, speed: 1.019, height: 0.139 },
      { kind: 'arrest', bone: 'R_Hand', at: 8.833, decel: 201.6, speed: 1.431, height: 0.6 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 8.9, decel: 104.7, speed: 1.389, height: 0.053 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 8.9, decel: 130.1, speed: 1.434, height: 0.033 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.167, decel: 125.8, speed: 0.583, height: 0.038 },
      { kind: 'plant', bone: 'L_ToeBase', at: 9.283, speed: 2.33, height: 0.136 },
      { kind: 'arrest', bone: 'L_Hand', at: 9.4, decel: 112.9, speed: 0.765, height: 0.626 },
      { kind: 'arrest', bone: 'R_Hand', at: 9.4, decel: 259.4, speed: 0.254, height: 0.68 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.4, decel: 130.8, speed: 0.698, height: 0.021 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.4, decel: 137.2, speed: 0.438, height: 0.042 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.567, decel: 57.2, speed: 0.719, height: 0.025 },
      { kind: 'arrest', bone: 'R_Hand', at: 9.633, decel: 225.3, speed: 2.194, height: 0.424 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.633, decel: 515, speed: 0.505, height: 0.284 },
      { kind: 'plant', bone: 'R_ToeBase', at: 9.7, speed: 1.796, height: 0.138 },
      { kind: 'arrest', bone: 'L_Hand', at: 9.8, decel: 240.3, speed: 0.561, height: 0.686 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 9.8, decel: 143.5, speed: 0.789, height: 0.047 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 9.8, decel: 178.2, speed: 0.674, height: 0.027 },
      { kind: 'driven', bone: 'Hip', at: 9.933, decel: 33.7 },
      { kind: 'plant', bone: 'L_ToeBase', at: 10.125, speed: 2.199, height: 0.138 },
      { kind: 'arrest', bone: 'L_ToeBase', at: 10.2, decel: 216.6, speed: 1.135, height: 0.029 },
    ],
  },
  'preset:biped:dance_04': {
    clip: 'preset:biped:dance_04', duration: 8.667, handPeak: 2.132, bodyMean: 0.215,
    events: [
      { kind: 'arrest', bone: 'L_Hand', at: 1.233, decel: 84.1, speed: 1.024, height: 0.726 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.399, decel: 64, speed: 0.165, height: 0.546 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.633, decel: 97.1, speed: 0.445, height: 0.711 },
      { kind: 'driven', bone: 'Hip', at: 1.799, decel: 25.6 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.032, decel: 42, speed: 0.939, height: 0.684 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.366, decel: 85.5, speed: 0.384, height: 0.758 },
      { kind: 'plant', bone: 'L_ToeBase', at: 2.445, speed: 0.761, height: 0.066 },
      { kind: 'driven', bone: 'Hip', at: 2.499, decel: 14.3 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.832, decel: 90.6, speed: 1.006, height: 0.785 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 2.832, decel: 115.7, speed: 0.574, height: 0.067 },
      { kind: 'driven', bone: 'Hip', at: 3.065, decel: 16.8 },
      { kind: 'arrest', bone: 'L_Hand', at: 3.398, decel: 90.4, speed: 0.313, height: 0.826 },
      { kind: 'driven', bone: 'Hip', at: 3.632, decel: 16.4 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 3.865, decel: 62.5, speed: 1.202, height: 0.067 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.098, decel: 36, speed: 0.982, height: 0.052 },
      { kind: 'driven', bone: 'Hip', at: 4.435, decel: 19.4 },
      { kind: 'plant', bone: 'L_ToeBase', at: 4.544, speed: 0.584, height: 0.068 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 4.835, decel: 107.8, speed: 0.907, height: 0.074 },
      { kind: 'driven', bone: 'Hip', at: 5.002, decel: 19.5 },
      { kind: 'plant', bone: 'R_ToeBase', at: 5.077, speed: 0.601, height: 0.056 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 5.135, decel: 43, speed: 0.66, height: 0.028 },
      { kind: 'driven', bone: 'Hip', at: 5.468, decel: 21.9 },
      { kind: 'plant', bone: 'L_ToeBase', at: 5.576, speed: 0.829, height: 0.073 },
      { kind: 'arrest', bone: 'L_Hand', at: 5.635, decel: 86.2, speed: 0.379, height: 0.863 },
      { kind: 'driven', bone: 'Hip', at: 5.868, decel: 21.2 },
      { kind: 'arrest', bone: 'R_Hand', at: 6.035, decel: 84.1, speed: 0.944, height: 0.602 },
      { kind: 'arrest', bone: 'R_ToeBase', at: 6.039, decel: 46, speed: 1.158, height: 0.095 },
      { kind: 'plant', bone: 'R_ToeBase', at: 6.043, speed: 0.73, height: 0.092 },
      { kind: 'driven', bone: 'Hip', at: 6.201, decel: 10.3 },
      { kind: 'arrest', bone: 'L_Hand', at: 6.434, decel: 57.6, speed: 0.706, height: 0.695 },
      { kind: 'driven', bone: 'Hip', at: 6.668, decel: 10.1 },
      { kind: 'driven', bone: 'Hip', at: 7.067, decel: 24.9 },
      { kind: 'arrest', bone: 'L_Hand', at: 7.634, decel: 57.9, speed: 0.755, height: 0.631 },
      { kind: 'driven', bone: 'Hip', at: 7.8, decel: 10 },
    ],
  },
  'preset:biped:dance_05': {
    clip: 'preset:biped:dance_05', duration: 2.333, handPeak: 4.417, bodyMean: 0.444,
    events: [
      { kind: 'arrest', bone: 'R_Hand', at: 0.2, decel: 141.6, speed: 1.162, height: 0.483 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.433, decel: 574.8, speed: 0.2, height: 0.382 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.433, decel: 559, speed: 0.359, height: 0.387 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.6, decel: 246.8, speed: 0.938, height: 0.562 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.6, decel: 183.9, speed: 0.543, height: 0.517 },
      { kind: 'arrest', bone: 'R_Hand', at: 0.767, decel: 167.6, speed: 1.729, height: 0.416 },
      { kind: 'arrest', bone: 'L_Hand', at: 0.833, decel: 370.2, speed: 0.49, height: 0.381 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.067, decel: 324.4, speed: 0.543, height: 0.622 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.233, decel: 535.3, speed: 0.733, height: 0.384 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.4, decel: 226.4, speed: 1.494, height: 0.58 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.467, decel: 241.7, speed: 0.488, height: 0.561 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.633, decel: 521.8, speed: 0.18, height: 0.403 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.633, decel: 536.1, speed: 0.433, height: 0.38 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.8, decel: 187.2, speed: 0.658, height: 0.516 },
      { kind: 'arrest', bone: 'R_Hand', at: 1.8, decel: 248.3, speed: 0.957, height: 0.571 },
      { kind: 'arrest', bone: 'L_Hand', at: 1.967, decel: 312.3, speed: 0.698, height: 0.425 },
      { kind: 'arrest', bone: 'R_Hand', at: 2.033, decel: 301.8, speed: 1.424, height: 0.404 },
      { kind: 'arrest', bone: 'L_Hand', at: 2.2, decel: 335.9, speed: 0.702, height: 0.588 },
    ],
  },
  'preset:biped:dance_06': {
    clip: 'preset:biped:dance_06', duration: 8.733, handPeak: 0.751, bodyMean: 0.031,
    events: [],
  },
  'preset:biped:idle': {
    clip: 'preset:biped:idle', duration: 15.375, handPeak: 0.066, bodyMean: 0.006,
    events: [],
  },
};

/** The events of one clip, or an empty budget if it was never measured. */
export function clipEvents(clip: string): ClipEvents {
  return CLIP_EVENTS[clip] ?? { clip, duration: 0, handPeak: 0, bodyMean: 0, events: [] };
}

/** Bones that count as a strike when a move is supposed to land with the hands. */
export const HANDS = ['L_Hand', 'R_Hand'];

/**
 * The single hardest stop in a clip — the frame worth building a move around.
 *
 * `only` restricts the search to a set of bones, and it matters more than it looks. box_01's
 * hardest arrest is a TOE at 87.2 H/s², beating its hand at 67.4, so an unrestricted search puts
 * the payoff of a move named for its punch down at the character's foot. A move declares which
 * limb it strikes with and the table answers for that limb.
 */
export function loudestArrest(clip: string, only?: readonly string[]): ClipEvent | null {
  const arrests = clipEvents(clip).events.filter(
    (e) => e.kind === 'arrest' && (!only || only.includes(e.bone)),
  );
  if (!arrests.length) return only ? loudestArrest(clip) : null;
  return arrests.reduce((a, b) => ((b.decel ?? 0) > (a.decel ?? 0) ? b : a));
}

/**
 * `n` well-SPACED peaks: the hardest arrest inside each of n equal windows.
 *
 * Taking the n loudest arrests outright does not work — they cluster. dance_05's five loudest all
 * fall inside three frames of each other at 0.433 and 1.633, so a move built on them fires five
 * times in two bursts and then runs silent for a second and a half. One peak per window forces the
 * beats apart while still landing every one of them on a frame the sweep actually found: for
 * dance_05 that gives 0.200, 0.433, 0.833, 1.233, 1.633 — roughly one every 350 ms.
 *
 * `until` shortens the search range, for a move whose last beat still needs room after it.
 */
export function beats(clip: string, n: number, options: { only?: readonly string[]; until?: number } = {}): ClipEvent[] {
  const table = clipEvents(clip);
  const span = options.until ?? table.duration;
  const arrests = table.events.filter(
    (e) => e.kind === 'arrest' && e.at < span && (!options.only || options.only.includes(e.bone)),
  );
  const out: ClipEvent[] = [];
  for (let i = 0; i < n; i += 1) {
    const from = (span * i) / n;
    const to = (span * (i + 1)) / n;
    const inWindow = arrests.filter((e) => e.at >= from && e.at < to);
    if (!inWindow.length) continue;
    out.push(inWindow.reduce((a, b) => ((b.decel ?? 0) > (a.decel ?? 0) ? b : a)));
  }
  return out;
}
