/**
 * Fasteners -- studs, rivets, bolts -- measured from the reference and placed on the frozen forms.
 *
 * TWO FAMILIES, because one hardware colour cannot be both. The belt and canister studs are brass and
 * the knee-pad bolts dark iron: measured medians 0x462e26 at saturation 0.483 against 0x2d2725 at
 * 0.188. An earlier version used one invented light blue-grey (0x8a8d92) for all of them, which is why
 * the bolts read as polished steel rather than as the dark warm iron they are.
 *
 * INSTANCED, not one mesh each. `grimoire/intake/detail_inventory.md` is explicit that a fastener is
 * "always an instanced system, never one-off meshes"; the previous 21 rivets were 21 separate meshes,
 * which also gave the viewer's picker 21 indistinguishable selectable objects.
 *
 * POSITIONS ARE RELATIVE TO THEIR PART, not to the frame -- the two assets place parts up to ~170 px
 * apart, so an absolute projection drops fasteners off the part. Depth comes from the baseline's front
 * surface, taken as the maximum over each stud's footprint, and x is clamped to the chord of the
 * part's cross-section at that depth. Four earlier placement attempts failed on exactly those two
 * points; see grimoire/build/cross_section_lofting.md.
 *
 * `belt` yields almost nothing because the baseline has no separate belt mesh -- node 1 is one
 * torso-and-arms shell -- so there is no belt surface to seat a stud on. That is the asset's limit,
 * not a detection failure.
 *
 * Generated by scripts/place_hardware.py; regenerate rather than edit.
 */

export type Stud = {
  /** World centre of the stud's base, on the part's front surface. */
  readonly position: readonly [number, number, number];
  readonly radius: number;
  /** How far it stands off the surface. */
  readonly height: number;
  readonly region: string;
  readonly family: 'brass' | 'iron';
};

/** 109 fasteners: belt brass 1, belt iron 4, boots brass 13, boots iron 9, canister brass 7, canister iron 3, knee-pads brass 21, knee-pads iron 32, pouches brass 9, pouches iron 10. */
export const STUDS: readonly Stud[] = [
  { position: [0.125, 0.5805, 0.1556], radius: 0.022, height: 0.0198, region: 'knee-pads', family: 'iron' },
  { position: [-0.0648, 0.4664, 0.0987], radius: 0.02, height: 0.018, region: 'knee-pads', family: 'iron' },
  { position: [-0.1081, 0.5391, 0.1359], radius: 0.0197, height: 0.0177, region: 'knee-pads', family: 'iron' },
  { position: [-0.108, 0.6245, 0.145], radius: 0.0179, height: 0.0161, region: 'knee-pads', family: 'iron' },
  { position: [0.2241, 1.4107, -0.0312], radius: 0.0073, height: 0.0066, region: 'belt', family: 'brass' },
  { position: [0.1446, 0.9476, 0.1121], radius: 0.0066, height: 0.006, region: 'canister', family: 'iron' },
  { position: [0.2419, 0.09, 0.1506], radius: 0.0042, height: 0.0038, region: 'boots', family: 'brass' },
  { position: [0.1974, 0.0838, 0.1315], radius: 0.0041, height: 0.0037, region: 'boots', family: 'brass' },
  { position: [-0.0077, 1.3257, 0.0811], radius: 0.0039, height: 0.0035, region: 'belt', family: 'iron' },
  { position: [0.1019, 0.7849, 0.1413], radius: 0.0037, height: 0.0033, region: 'canister', family: 'iron' },
  { position: [-0.1203, 0.5512, 0.1317], radius: 0.0036, height: 0.0032, region: 'knee-pads', family: 'brass' },
  { position: [-0.1367, 0.5091, 0.1144], radius: 0.0036, height: 0.0033, region: 'knee-pads', family: 'iron' },
  { position: [-0.0672, 1.2982, -0.0782], radius: 0.0035, height: 0.0031, region: 'belt', family: 'iron' },
  { position: [-0.1072, 0.0833, 0.1531], radius: 0.0035, height: 0.0032, region: 'boots', family: 'brass' },
  { position: [0.1473, 0.5454, 0.1489], radius: 0.0034, height: 0.0031, region: 'knee-pads', family: 'iron' },
  { position: [-0.1615, 0.6005, 0.0473], radius: 0.0032, height: 0.0029, region: 'knee-pads', family: 'brass' },
  { position: [0.205, 0.0161, 0.1646], radius: 0.0032, height: 0.0029, region: 'boots', family: 'iron' },
  { position: [0.1566, 1.4197, -0.0009], radius: 0.0031, height: 0.0028, region: 'belt', family: 'iron' },
  { position: [0.1055, 1.3901, 0.0315], radius: 0.003, height: 0.0027, region: 'belt', family: 'iron' },
  { position: [0.1106, 0.8683, 0.1453], radius: 0.003, height: 0.0027, region: 'canister', family: 'brass' },
  { position: [0.105, 0.7878, 0.1462], radius: 0.003, height: 0.0027, region: 'canister', family: 'brass' },
  { position: [0.1498, 0.6731, 0.032], radius: 0.0029, height: 0.0026, region: 'knee-pads', family: 'brass' },
  { position: [-0.0391, 0.1367, 0.008], radius: 0.0029, height: 0.0026, region: 'boots', family: 'brass' },
  { position: [-0.0795, 0.6106, 0.1437], radius: 0.0028, height: 0.0025, region: 'knee-pads', family: 'iron' },
  { position: [0.1142, 0.4744, 0.0912], radius: 0.0028, height: 0.0025, region: 'knee-pads', family: 'brass' },
  { position: [0.1405, 0.9515, 0.112], radius: 0.0028, height: 0.0025, region: 'canister', family: 'brass' },
  { position: [0.194, 0.5568, 0.1466], radius: 0.0027, height: 0.0024, region: 'knee-pads', family: 'brass' },
  { position: [-0.0809, 0.5802, 0.1409], radius: 0.0026, height: 0.0023, region: 'knee-pads', family: 'iron' },
  { position: [-0.1397, 0.5428, 0.135], radius: 0.0026, height: 0.0023, region: 'knee-pads', family: 'iron' },
  { position: [0.2403, 0.1337, 0.0527], radius: 0.0025, height: 0.0023, region: 'boots', family: 'brass' },
  { position: [0.1346, 0.8018, 0.1368], radius: 0.0025, height: 0.0022, region: 'canister', family: 'brass' },
  { position: [-0.0669, 0.4432, 0.0509], radius: 0.0024, height: 0.0021, region: 'knee-pads', family: 'iron' },
  { position: [0.1154, 0.5639, 0.1381], radius: 0.0024, height: 0.0022, region: 'knee-pads', family: 'brass' },
  { position: [0.1024, 0.4624, 0.0339], radius: 0.0024, height: 0.0022, region: 'knee-pads', family: 'brass' },
  { position: [0.118, 0.8855, 0.1388], radius: 0.0023, height: 0.0021, region: 'canister', family: 'brass' },
  { position: [0.1403, 0.9397, 0.1119], radius: 0.0023, height: 0.0021, region: 'canister', family: 'iron' },
  { position: [-0.0817, 0.4807, 0.105], radius: 0.0022, height: 0.002, region: 'knee-pads', family: 'iron' },
  { position: [0.1592, 0.459, 0.0865], radius: 0.0022, height: 0.002, region: 'knee-pads', family: 'brass' },
  { position: [0.1247, 0.4933, 0.1248], radius: 0.0022, height: 0.002, region: 'knee-pads', family: 'iron' },
  { position: [0.2318, 0.0825, 0.1571], radius: 0.0022, height: 0.002, region: 'boots', family: 'brass' },
  { position: [0.2418, 0.0794, 0.1568], radius: 0.0021, height: 0.0019, region: 'boots', family: 'brass' },
  { position: [0.2192, 0.1136, 0.0881], radius: 0.0021, height: 0.0019, region: 'boots', family: 'iron' },
  { position: [0.1317, 0.9277, 0.1459], radius: 0.0021, height: 0.0019, region: 'canister', family: 'brass' },
  { position: [-0.1019, 0.4513, 0.0539], radius: 0.002, height: 0.0018, region: 'knee-pads', family: 'brass' },
  { position: [-0.1308, 0.4078, 0.0355], radius: 0.002, height: 0.0018, region: 'knee-pads', family: 'brass' },
  { position: [0.1813, 0.5929, 0.1548], radius: 0.002, height: 0.0018, region: 'knee-pads', family: 'iron' },
  { position: [0.1932, 0.5243, 0.1427], radius: 0.002, height: 0.0018, region: 'knee-pads', family: 'iron' },
  { position: [-0.1112, 0.6219, 0.1296], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [-0.125, 0.5232, 0.1261], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [-0.1136, 0.6056, 0.1448], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [-0.0863, 0.6021, 0.1436], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [-0.0999, 0.5988, 0.1435], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [-0.1068, 0.5489, 0.1352], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [0.133, 0.6609, 0.0298], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [0.1787, 0.659, 0.0287], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [0.1231, 0.4466, 0.0475], radius: 0.0019, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [0.2309, 0.0022, 0.1692], radius: 0.0019, height: 0.0017, region: 'boots', family: 'iron' },
  { position: [-0.1152, 0.5579, 0.1342], radius: 0.0018, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [-0.0884, 0.4463, 0.0537], radius: 0.0018, height: 0.0017, region: 'knee-pads', family: 'brass' },
  { position: [-0.1624, 0.5392, 0.0865], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'brass' },
  { position: [-0.0813, 0.5753, 0.1428], radius: 0.0018, height: 0.0017, region: 'knee-pads', family: 'iron' },
  { position: [-0.081, 0.6184, 0.1453], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [-0.0754, 0.6061, 0.1437], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [-0.032, 0.5754, 0.1229], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [-0.1149, 0.4962, 0.1033], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [-0.0883, 0.4673, 0.0753], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [0.1177, 0.4905, 0.1124], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'brass' },
  { position: [0.1112, 0.4778, 0.0769], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'brass' },
  { position: [0.1664, 0.5736, 0.1499], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [0.1347, 0.4869, 0.1234], radius: 0.0018, height: 0.0016, region: 'knee-pads', family: 'iron' },
  { position: [-0.1013, 0.1291, 0.0598], radius: 0.0018, height: 0.0017, region: 'boots', family: 'brass' },
  { position: [0.2378, 0.0807, 0.1572], radius: 0.0018, height: 0.0016, region: 'boots', family: 'brass' },
  { position: [-0.1648, 0.5268, 0.0567], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'brass' },
  { position: [-0.0905, 0.5164, 0.1332], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'iron' },
  { position: [0.1562, 0.4117, 0.0562], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'brass' },
  { position: [0.1435, 0.5841, 0.1556], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'iron' },
  { position: [0.1289, 0.5244, 0.1422], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'iron' },
  { position: [0.1587, 0.4174, 0.0567], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'iron' },
  { position: [0.1673, 0.4122, 0.057], radius: 0.0017, height: 0.0015, region: 'knee-pads', family: 'iron' },
  { position: [-0.0759, 0.0859, 0.1504], radius: 0.0017, height: 0.0015, region: 'boots', family: 'iron' },
  { position: [-0.0968, 0.0715, 0.1612], radius: 0.0016, height: 0.0015, region: 'boots', family: 'brass' },
  { position: [0.1255, 0.8812, 0.1453], radius: 0.0016, height: 0.0014, region: 'canister', family: 'brass' },
  { position: [-0.0676, 0.7621, 0.15], radius: 0.0015, height: 0.0014, region: 'pouches', family: 'brass' },
  { position: [-0.1009, 0.0756, 0.1607], radius: 0.0015, height: 0.0014, region: 'boots', family: 'brass' },
  { position: [-0.0773, 0.0918, 0.143], radius: 0.0015, height: 0.0013, region: 'boots', family: 'brass' },
  { position: [-0.0724, 0.0526, 0.1682], radius: 0.0015, height: 0.0013, region: 'boots', family: 'iron' },
  { position: [0.2076, 0.1065, 0.0889], radius: 0.0015, height: 0.0014, region: 'boots', family: 'iron' },
  { position: [-0.1053, 0.0742, 0.1584], radius: 0.0013, height: 0.0012, region: 'boots', family: 'brass' },
  { position: [-0.0281, 0.042, 0.1383], radius: 0.0013, height: 0.0012, region: 'boots', family: 'iron' },
  { position: [-0.0891, 0.1223, 0.0724], radius: 0.0012, height: 0.0011, region: 'boots', family: 'iron' },
  { position: [-0.0878, 0.1194, 0.0822], radius: 0.0012, height: 0.0011, region: 'boots', family: 'iron' },
  { position: [-0.0768, 0.7126, 0.1368], radius: 0.0009, height: 0.0008, region: 'pouches', family: 'brass' },
  { position: [0.1198, 0.6595, 0.1464], radius: 0.0009, height: 0.0008, region: 'pouches', family: 'brass' },
  { position: [0.1073, 0.6208, 0.1439], radius: 0.0008, height: 0.0008, region: 'pouches', family: 'brass' },
  { position: [0.1007, 0.7189, 0.1303], radius: 0.0006, height: 0.0006, region: 'pouches', family: 'iron' },
  { position: [-0.0852, 0.738, 0.1207], radius: 0.0005, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [-0.0841, 0.7477, 0.1279], radius: 0.0004, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [-0.0866, 0.7475, 0.1279], radius: 0.0004, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [-0.0216, 0.8994, 0.1198], radius: 0.0004, height: 0.0003, region: 'pouches', family: 'iron' },
  { position: [0.1005, 0.7045, 0.1327], radius: 0.0004, height: 0.0003, region: 'pouches', family: 'brass' },
  { position: [0.1058, 0.6407, 0.1424], radius: 0.0004, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [0.1737, 0.7049, 0.1196], radius: 0.0004, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [0.1044, 0.6482, 0.1423], radius: 0.0004, height: 0.0004, region: 'pouches', family: 'iron' },
  { position: [0.1021, 0.6481, 0.1423], radius: 0.0004, height: 0.0003, region: 'pouches', family: 'iron' },
  { position: [-0.0834, 0.8063, 0.1196], radius: 0.0003, height: 0.0003, region: 'pouches', family: 'brass' },
  { position: [-0.0591, 0.8452, 0.1242], radius: 0.0003, height: 0.0003, region: 'pouches', family: 'brass' },
  { position: [-0.0134, 0.8817, 0.1164], radius: 0.0003, height: 0.0003, region: 'pouches', family: 'iron' },
  { position: [0.1012, 0.694, 0.1357], radius: 0.0003, height: 0.0003, region: 'pouches', family: 'brass' },
  { position: [0.1233, 0.7244, 0.1268], radius: 0.0003, height: 0.0003, region: 'pouches', family: 'brass' },
];
